### ISSUE TITLE
How can i add custom fields for a payments

### ISSUE THREAD

**Issue by moorthysubu** [mposSVK/acceptSDK-Android#10]
Hey Wirecard,

I need to add custom fields like few id's and details during start payment.Then while Need to get it back while am accessing that particular payment unique id.In that payment model there is a data (getCustomFields() as hashMap ). How can i give input for this data..

Thanks in advance

**Comment by WirecardMobileServices** [comment]
Payment item object is having "note", in new versions of SDK its planned to add some kind of support for this.
