### ISSUE TITLE
App crashes after calling signatureRequest.signatureEntered

### ISSUE THREAD

**Issue by doerschner** [mposSVK/acceptSDK-Android#11]
Hey,
when I try to call PaymentFlowController.SignatureRequest.signatureEntered(...) my App crashes if I am on a Motorola Nexus. On other phones it seems to ignore it and restarts the activity.

my stacktrace:
05-29 13:39:05.202 11369 12039 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #12
05-29 13:39:05.202 11369 12039 E AndroidRuntime: Process: com.my.app, PID: 11369
05-29 13:39:05.202 11369 12039 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at android.os.AsyncTask$3.done(AsyncTask.java:318)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at java.lang.Thread.run(Thread.java:761)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No static method create(Ljava/lang/String;[Lorg/apache/http/NameValuePair;)Lorg/apache/http/entity/ContentType; in class Lorg/apache/http/entity/ContentType; or its super classes (declaration of 'org.apache.http.entity.ContentType' appears in /data/app/com.my.app-1/split_lib_dependencies_apk.apk:classes33.dex)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at org.apache.http.entity.mime.MultipartEntityBuilder.buildEntity(MultipartEntityBuilder.java:219)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at org.apache.http.entity.mime.MultipartEntity.getEntity(MultipartEntity.java:119)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at org.apache.http.entity.mime.MultipartEntity.writeTo(MultipartEntity.java:180)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at de.wirecard.accept.sdk.CustomRequest.doInBackground(CustomRequest.java:243)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at de.wirecard.accept.sdk.CustomRequest.doInBackground(CustomRequest.java:47)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at android.os.AsyncTask$2.call(AsyncTask.java:304)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-29 13:39:05.202 11369 12039 E AndroidRuntime: ... 4 more

**Comment by WirecardMobileServices** [comment]
Hi,
if its still actual pls reopen this issue. Looks like its smartphone native byte array handling related.
