### ISSUE TITLE
App crashes after calling AcceptSDK.init([...])

### ISSUE THREAD

**Issue by doerschner** [mposSVK/acceptSDK-Android#13]
version 1.5.10.1.
The app crashes with the following log after calling AcceptSDK.init(Context, String, String, String):
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/scottyab/rootbeer/RootBeer;
    at de.wirecard.accept.sdk.AcceptSDK.checkRooted(AcceptSDK.java:343)
    at de.wirecard.accept.sdk.AcceptSDK.init(AcceptSDK.java:324)
```

**Comment by WirecardMobileServices** [comment]
Probably required project cleanup, and build ...
it is used com.scottyab:rootbeer-lib:0.0.6 for check if device is rooted

**Comment by doerschner** [comment]
Sadly, cleaning and rebuilding didn't help. Still the same crash. 
De- and reinstalling didn't help either.

The device is not rooted, I don't know what you mean with the second sentence :/

**Comment by WirecardMobileServices** [comment]
I am sorry, looks like local build problems with RootBeer class
This is class responsible for root check, and for this we are using
dependency to "com.scottyab:rootbeer-lib:0.0.6"

try to add ..(just try to test if dependency is working correctly) 
_compile ' com.scottyab:rootbeer-lib:0.0.6'_
into Your project build.gradle file 

From logs its looking like local build problem.
It can happen that JitPack is having some problems...it was happening to us in past (few weeks ago) with different libraries. Its quite unusual that this class not found. It is working for more projects.

**Comment by doerschner** [comment]
That worked, thank you. (though i guess that this fix is more a 'hotfix' than a real problem solver, isn't it?)
