### ISSUE TITLE
Class not found 

### ISSUE THREAD

**Issue by AndroidLoaders** [mposSVK/acceptSDK-Android#15]
I need to make an android application that accepts payment from mobile devices(mPOS) using attached card readers(i.e Swipe card and make payment , no need to add card details manually). We have selected bbPOS Chipper™ OTA for our app.
     
Also we are trying to load demo project provided at this link but when we tried to import it into Android Studio it is showing class not found error for class AcceptBbposPaymentFlowController inside PaymentFlowActivity class(Image_1 is attached). We tried to find this class using this link provided in quick start guide(documentation of project) but found 404 error.Also updated all gradle files to latest versions(Image_3 is attached)

We did  not find any proper support link accept this email link. After importing this demo project Android support plugin stops working(Image_2 is attached).

In documentation of project, it is mentioned that obtain ClientID, Secret, API path from Accept Support Team, but how do we contact Accept Support Team is not mentioned.

Their is no details available on how to create merchant account and it's maintenance. So provide proper support for integration of payment.

![image_2](https://user-images.githubusercontent.com/20015082/30856548-574d107a-a2d6-11e7-9a55-739073e7f605.png)
![image_1](https://user-images.githubusercontent.com/20015082/30856549-574f4282-a2d6-11e7-95f0-9e6857e3e00e.png)
![image_3](https://user-images.githubusercontent.com/20015082/30856644-a1785ccc-a2d6-11e7-909f-e371d376d92e.png)

**Comment by WirecardMobileServices** [comment]
Fixed in new version of SDK 1.6.0
