### ISSUE TITLE
NullReferenceException if calling startPaymentFlow

### ISSUE THREAD

**Issue by doerschner** [mposSVK/acceptSDK-Android#16]
Hey,

i got a new issue. 
I am calling:
`paymentFlowController.startPaymentFlow(device, amountUnits, amountCurrency, paymentFlowDelegate);`
`paymentFlowController` is initialized with: `new AcceptThyronPaymentFlowController(false, true, false, false);`
If I debug, it seems that this line: `final ThyronController thyronController = (ThyronController)AcceptSDK.getCNPController();` is returning null.

Versions are:
AcceptSDK 1.5.10.2
AcceptSDK extension spire 1.5.9.2 

Would be nice if you could solve this as soon as possible :)

**Comment by jakubmisko** [comment]
Hello,

your problem is probably because you haven't called 
`AcceptSDK.loadExtensions(this, null, contactless, usb);`
before you call `startPaymentFlow()`. Therefore SDK is not fully initialized. For more information check guides in docs folder.

**Comment by doerschner** [comment]
Thank you for your answer. But it is currently called like this:
`AcceptSDK.init(appContext.getApplicationContext(), CLIENT_ID, CLIENT_SECRET, API_PATH);
AcceptSDK.loadExtensions(appContext.getApplicationContext(), null, false);
AcceptSDK.setPrefTimeout(7); //timeout for requests
AcceptSDK.setPaymentCallbackURL(CALLBACK_URL);`

Is this the wrong way? Do I have to call another `loadExtensions` Method?

**Comment by jakubmisko** [comment]
Looks ok. Can you provide us more informations? Stack trace or some code fragments where problem occurs?

**Comment by doerschner** [comment]
I'm afraid there is not much more I can show you. The rest is our code and, or so I guess, stuff you can't make any use of.
the one this that is not from our side are this lines:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void de.wirecard.accept.extension.thyron.ThyronController.setWaitForConfirmationForOffline(boolean)' on a null object reference at de.wirecard.accept.extension.refactor.AcceptThyronPaymentFlowController.startPaymentFlow(AcceptThyronPaymentFlowController.java:300)`

I will keep searching and commenting if I find something that sounds useful

**Comment by WirecardMobileServices** [comment]
Explained. 
Propose to use new version of SDK 1.6.0
