### ISSUE TITLE
New version documentation

### ISSUE THREAD

**Issue by joaovrodrigues** [mposSVK/acceptSDK-Android#17]
Hey guys,

It seems that some changes have been introduced in version 1.5.10 that the documentation does not reflect.

To name a couple there are now extra parameters in the `loadExtensions` method, some inner classes have been moved to an upper level and it seems to be dependent on the rootbeer library, not sure which version, though.

Where can I see the changelog and/or updated docs?

Thank you very much!

**Comment by WirecardMobileServices** [comment]
Sure we are working on update of documentation.
In the meanwhile pls try to use :
[Demo app source code](https://github.com/WirecardMobileServices/acceptSDK-Android/tree/master/demo/demo)
thx.
