### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by VenkateshDoodleBlue** [mposSVK/acceptSDK-Android#18]
Process: de.wirecard.accept.sample.thyron, PID: 14355  java.lang.IllegalArgumentException: Device has not ThyronBluetoothDevice instance  at de.wirecard.accept.extension.thyron.hardware.bt.Bluetooth.connect(Bluetooth.java:293) at de.wirecard.accept.extension.thyron.ThyronController$17$1.run(ThyronController.java:1125)  at android.os.Handler.handleCallback(Handler.java:739)  at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5442) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

At first time connecting with the termial,once the termial configuration completed and termial restarted...
App crashed and giving IllegalArgumentException....Can you give any solution to solve this problem

**Comment by RadoslavDanko** [comment]
Hi,

I would like to make you aware of our new SDK which is to supersede the acceptSDK-Android and is using our new payment infrastructure.

You can find the new SDK in here:
https://github.com/WirecardMobileServices/SuprAcceptSDK-Android

The comprehensive integration guide is also available:
https://wirecardmobileservices.github.io/SuprAcceptSDK-Developer/

**Comment by VenkateshDoodleBlue** [comment]
Hi,
Thanks for the response. We are already in production so cannot change the entire sdk to new. so can you please suggest us to find the solution for this issue. we are currently using 1.5.9 with spire 1.5.8 as per your doc. 

It would be great. if we solve it without moving to another SDK.
Looking forward.

**Comment by RadoslavDanko** [comment]
No worries - I already forwarded info to our Android dev team and they will be in touch.
I would like to emphasise however that we plan to deprecate the current acceptSDK in autumn next year in favour of our new product which have more functionality available.

**Comment by WirecardMobileServices** [comment]
Hi, 
Looks like you are using abstract instance of ThyronBluetoothDevice or something like this. (I am Sorry its to old version, ThyronBluetoothDevice was renamed in 1.5.10 version to SpireBluetoothDevice) ... i propose to use newest version of SDK if its posiible. (SDK 1.5.10.2 / Spire 1.5.9.2) , it is not so much changes in next versions if we compare  SDK 1.5.9.
(biggest change is rename Thyron/Spire) .. and some improvements without implementation requirements.

In case of connecting device pls use object, you received from discoverDevices method.

PS: We are finalizing the latest version of this solution.

**Comment by WirecardMobileServices** [comment]
Fixed in new version of SDK 1.6.0

**Comment by VenkateshDoodleBlue** [comment]
Thanks for ur response,We will try to solve this....
