### ISSUE TITLE
Adding library leads to packaging error with duplicated jackson files

### ISSUE THREAD

**Issue by mpost** [mposSVK/acceptSDK-Android#2]
The following build error is caused by just adding the jitpack dependency to an android project:

``` java
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/services/com.fasterxml.jackson.core.JsonFactory
    File1: C:\Users\mpost\git\payment-accept\app\build\intermediates\exploded-aar\com.github.mposSVK\acceptSDK-Android\1.4.10\jars\libs\jackson-core-2.2.3.jar
    File2: C:\Users\mpost\git\payment-accept\app\build\intermediates\exploded-aar\com.github.mposSVK\acceptSDK-Android\1.4.10\jars\libs\jackson-dataformat-csv-2.2.3.jar

```

Need to add jackson to exludes list:

``` java
exclude 'META-INF/services/com.fasterxml.jackson.core.JsonFactory'
```

**Comment by Rojasri** [comment]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.

> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/com.nineoldandroids/library/pom.properties
>     File1: C:\Users\krish.gradle\caches\modules-2\files-2.1\com.nineoldandroids\library\2.4.0\e9b63380f3a242dbdbf103a2355ad7e43bad17cb\library-2.4.0.jar
>     File2: C:\Users\krish\AndroidStudioProjects\Cabily3\app\build\intermediates\exploded-aar\com.specyci\residemenu\1.6\jars\libs\nineoldandroids-library-2.4.0.jar   

This is My Error What I need to Add in exludes list

**Comment by WirecardMobileServices** [comment]
Hi mpost,
nineoldandroids-library-2.4.0.jar will be removed in next release of SDK lib.
thx.

**Comment by Rojasri** [comment]
How  we rectify this Error ?
How Compile Without Exceptions. Please give me Suggestion

**Comment by isaachambers** [comment]
Rojasri add 

   packagingOptions {
        exclude 'META-INF/maven/com.nineoldandroids/library/pom.xml'
        exclude 'META-INF/maven/com.nineoldandroids/library/pom.properties'
    }

to your build file
