### ISSUE TITLE
NullPointerException: CNPController.enableAdapter()' on a null object reference

### ISSUE THREAD

**Issue by VenkateshDoodleBlue** [mposSVK/acceptSDK-Android#20]
Hey Guys,

  We are updating our sdk from 1.5.9 to 1.6.1 and Spire 1.5.8 to 1.6.1, We are facing lots of problems please help out from this.
   

caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void de.wirecard.accept.sdk.cnp.CNPController.enableAdapter()' on a null object reference 

 In your new quick guide your not talked about the CNPController itself, im calling this method for enables the CNPController but in updated sdk 1.6.1 this method is deprecated so its showing NullPointerException,Please share us what is the alternative method for this,it will be more needful for us.

Thanks.

**Comment by WirecardMobileServices** [comment]
Will be fixed here:
https://github.com/WirecardMobileServices/acceptSDK-Android/issues/21
