### ISSUE TITLE
NullPointerException: ThyronController.setWaitForConfirmationForOffline(boolean)' on a null object reference

### ISSUE THREAD

**Issue by VenkateshDoodleBlue** [mposSVK/acceptSDK-Android#21]
Hi Team,
  
We are updating our sdk from **1.5.9 to 1.6.1 and Spire 1.5.8 to 1.6.1**  , We are facing lots of problems please help out from this.

java.lang.NullPointerException: Attempt to invoke virtual method '**void de.wirecard.accept.extension.thyron.ThyronController.setWaitForConfirmationForOffline(boolean)**' on a null object reference

We are calling startPaymentFlow -->  getPaymentFlowController().startPaymentFlow(device, amountUnits, amountCurrency, paymentFlowDelegate);

Inside sdk **AcceptThyronPaymentFlowController** Class 

 public void startPaymentFlow(Device lDevice, long amount, final Currency currency, final PaymentFlowDelegate delegate) throws IllegalStateException {
        this.testDevicePresetOrUseThis(lDevice);
        L.e(TAG, ">>> start payment flow");
        this.lastTransactionFromPreauth = null;
        final ThyronController thyronController = (ThyronController)AcceptSDK.getCNPController();
        **thyronController.setWaitForConfirmationForOffline(true);**
        thyronController.setSepaTransaction(this.sepa);
        AcceptSDK.setPaymentTransactionType(this.sepa?TransactionType.SEPA_PAYMENT:TransactionType.CARD_PAYMENT);
        AcceptSDK.getCNPController().setCNPListener(new CNPListener() {
            public void onTerminalEvent(TerminalEvent terminalEvent) {
                Log.d(AcceptThyronPaymentFlowController.TAG, "terminalEvent " + terminalEvent.name());
                switch(null.$SwitchMap$de$wirecard$accept$sdk$cnp$observer$TerminalEvent[terminalEvent.ordinal()]) {
                case 1:
                case 6:
                    if(delegate != null) {
                        delegate.onPaymentFlowUpdate(Update.DONE);
                    }
                    break;
                case 2:
                    if(delegate != null) {
                        delegate.onPaymentFlowUpdate(Update.CONFIGURATION_UPDATE);
                    }
                    break;
                case 3:
                    if(delegate != null) {
                        delegate.onPaymentFlowUpdate(Update.CONFIGURATION_UPDATE_AVAILABLE);
                    }
                    break;
                case 4:
                    if(delegate != null) {
                        delegate.onPaymentFlowUpdate(Update.FIRMWARE_UPDATE_AVAILABLE);
                    }
                    break;
                case 5:
                    if(delegate != null) {
                        delegate.onPaymentFlowUpdate(Update.FIRMWARE_UPDATE);
                    }
                }

            }

This error is coming form sdk how to solve this problem? Please help us out from this

**Comment by WirecardMobileServices** [comment]
Hello VenkateshDoodleBlue.
Very hard to identify why this is appearing ...looks like:
`AcceptSDK.loadExtensions(Context context, String defFromSharedPref, boolean supportContactLess, boolean useUsb;`
was not called. Pls follow implementation example here:
https://github.com/WirecardMobileServices/acceptSDK-Android/blob/master/demo/demo/sample/src/main/java/de/wirecard/accept/sample/Application.java

Process flow is simple: initSDK and then  load extensions(because you are able to use more extensions..)
....
everything is desribed with examples here: https://github.com/WirecardMobileServices/acceptSDK-Android/blob/master/docs/AcceptSDK_Android%20-%20Quick%20Start%20Guide.pdf
