### ISSUE TITLE
Application.onTerminate() should not be used to .finish() the AcceptSDK

### ISSUE THREAD

**Issue by mpost** [mposSVK/acceptSDK-Android#4]
This code will never be called on production devices:

https://github.com/mposSVK/acceptSDK-Android/blob/master/demo/demo/sample/src/main/java/de/wirecard/accept/sample/Application.java#L85

According to the documentation:

> This method is for use in emulated process environments. It will never be called on a production Android device, where processes are removed by simply killing them; no user code (including this callback) is executed when doing so.

http://developer.android.com/reference/android/app/Application.html#onTerminate()

**Comment by WirecardMobileServices** [comment]
Ok, thx.
Good Poit.
