### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by vogelt** [mposSVK/acceptSDK-Android#9]
Hi guys,

the issue https://github.com/mposSVK/acceptSDK/issues/13 exists also for the android sdk.

Error{type=IO, optionalException=javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found., httpErrorCode=-1, optionalBody=null}

**Comment by WirecardMobileServices** [comment]
Sorry about that, we will add certificate to keystore as sun as possible.

**Comment by vogelt** [comment]
Thank you - with Version 1.5.6.2 the SDK works as expected!
